### ISSUE TITLE
Terrain painting stays in mouse pressed state when losing node focus

### ISSUE THREAD

**Issue by outobugi** [ozzr/godot_terrain#1]
When height painting and losing focus of the Terrain by dragging mouse over the terrain and then refocusing the Terrain Node, it continues painting. Meaning the mouse pressed state is never released when node focus changes. I would assume this is a problem with texture painting as well.

**Comment by ozzr** [comment]
Hi, thanks for notifying the issue!!🎉
I think I know exactly what may have been causing the issue and where to fix it.
 
PS: Sorry for the delay, creating tutorials is harder than I thought 🤣 and it is consuming a lot of time

**Comment by ozzr** [comment]
I haven't been able of replicating the issue, but, I added some new lines of code that "should" fix it. The issue as you said, might be caused by the editor not clearing the stored pressed state when out of the spatial  viewport. I will keep the issue open until the new version is out and could be tested. Thank you!!
